services:
  create.event.jwt_created_listener:
    class: App\Apis\CustomerPortal\EventListener\JWTCreatedEventSubscriber
    arguments: ["@request_stack"]
    tags:
      - {
          name: kernel.event_listener,
          event: lexik_jwt_authentication.on_jwt_created,
          method: onJWTCreated,
        }

  decode.event.jwt_decoded_listener:
    class: App\Apis\CustomerPortal\EventListener\JWTDecodedEventSubscriber
    arguments: ["@request_stack"]
    tags:
      - {
          name: kernel.event_listener,
          event: lexik_jwt_authentication.on_jwt_decoded,
          method: onJWTDecoded,
        }

  invalid.event.jwt_invalid_listener:
    class: App\Apis\CustomerPortal\EventListener\JWTInvalidEventSubscriber
    arguments: ["@request_stack"]
    tags:
      - {
          name: kernel.event_listener,
          event: lexik_jwt_authentication.on_jwt_not_found,
          method: onJWTNotFound,
        }

  expired.event.jwt_expired_listener:
    class: App\Apis\CustomerPortal\EventListener\JWTExpiredEventSubscriber
    arguments: ["@request_stack"]
    tags:
      - {
          name: kernel.event_listener,
          event: lexik_jwt_authentication.on_jwt_expired,
          method: onJWTExpired,
        }
